### ISSUE TITLE
Sublime text 3 asks me to choose a default language whenever I open it

### ISSUE THREAD

**Issue by elieobeid7** [acabin/docphp#4]
Ever since I installed that plugin I get this issue

https://forum.sublimetext.com/t/sublime-text-3-asks-me-to-choose-a-default-language-whenever-i-open-it/21561/

Please fix it

**Comment by garveen** [comment]
Does this plugin's other things functioning well?
Please paste your Preferences > Package Settings > DocPHPManualer > Settings - User

**Comment by elieobeid7** [comment]
I don't know about all the other things, but they seem to work, but I haven't use it for a long time so not so sure

and here's what you asked for, that's for user

```
{
    "language": "en",
    "language_fallback": "en",
    "languages":
    {
        "en": "gz"
    }
}

```

and that's the default

```
{
    // Show manual automatically
    "auto": false,

    // Delay after cursor finish moving, in microseconds
    "auto_delay": 500,

    // Debug mode
    "debug": false,

    // Search user defined symbols
    "search_user_symbols": true,

    // Select language
    "language": false,

    // Select fallback language
    "language_fallback": false,

    // Available languages
    "languages": {},

    // Max height and width of popup
    "popup_max_height": 1080,
    "popup_max_width": 1280,

    // Prompt "not found" when symbol not found
    "prompt_when_not_found": true,

    // Use the panel on the bottom instead of popup
    "use_panel": false
}

```

**Comment by garveen** [comment]
Because this is a small package so I didn't have a debug mode on it.

You could help me to find out what happened with these steps:
1. Extract the DocPHPManualer.sublime-package which located at <sublime/Data/Installed Packages> with a zip tool to <sublime/Data/Packages>
2. Add these two line to docphp.py after line 585, at DocphpCheckoutLanguageCommand->run
       import traceback
       traceback.print_stack()
3. Restart your SublimeText, and open the console, there should be some traceback info
4. Paste those info to here
